### PR TITLE
RT-CAN: enable build of xeno_can, virtual can interface

### PR DESCRIPTION
**Pull request by mhaberler**
Robert - this is a preparatory step for RTCAN-enabling the BB xenomai kernel

The BB RT-CAN driver by Steve Botazzo needs a bit of polishing and will live out of tree on my github repo until we have it merge-ready and it trickles down through the Xenomai repo.

it'be great if we could have the basic support in-kernel in your next iteration!

thanks, - Michael

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks, merged up;
https://github.com/RobertCNelson/bb-kernel/commit/b05b6fbabaa669cb4f864e1ffdce1ea8e2a6c327

Just let me know when you get the can driver tweaked and i'l push out r71.. 

Regards,

**Comment by mhaberler** [comment]
super, thanks! working on it right now.

roughly how long does it take until a new kernel rev appears (ie whats your trigger)?

**Comment by RobertCNelson** [comment]
Right now i've been mostly frozen on r70, just in case CircuitCo has a problem flashing their "new" image..  I belive that's all done now, so it's pretty safe to jump to r71 for the builds..  Usually i like to keep it to one build a week.  If you guys don't need anything else then just this config change for the moment, i can kick off a build now. ;)

**Comment by mhaberler** [comment]
no, nothing for now; the tweaked driver will take a while to get sorted, but having the kernel with xeno_can available to work against would be really helpful

**Comment by RobertCNelson** [comment]
and pushed out.  Right now i'm only running at about half capacity with 4 wand quad's as my two omap5's are currently down.  So it should be all synced out by late afternoonish...

Regards,

**Comment by mhaberler** [comment]
-r71 works as expected, and the out-of-tree driver at https://github.com/mhaberler/rtcan-bb/tree/mah does move the motor - so above water.

thanks!

**Pull request closed without merging**
